{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.eazybankcommon.service.port }}
      targetPort: {{ .Values.eazybankcommon.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.eazybankcommon.service.type }}
{{- end -}}